import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import css from "../styles/Home.module.css";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
    const { data, isLoading } = trpc.useQuery([
        "example.hello",
        { text: "from tRPC" },
    ]);

    const { data: session } = useSession();

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={css.main}>
                <h3>{"Would thou dare ...?"}</h3>
                <div className={css.options}>
                    <div className={css.option}></div>
                    <div>vs</div>
                    <div className={css.option}></div>
                </div>
            </div>
        </>
    );
};

export default Home;
